### ISSUE TITLE
New faster GitHub pages

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy_doc#12]
I keep getting a warning mail from GH stating this:

```
The page build completed successfully, but returned the following warning:

GitHub Pages recently underwent some improvements (https://github.com/blog/1715-faster-more-awesome-github-pages) to make your site faster and more awesome, but we've noticed that docs.sympy.org isn't properly configured to take advantage of these new features. While your site will continue to work just fine, updating your domain's configuration offers some additional speed and performance benefits. Instructions on updating your site's IP address can be found at https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages, and of course, you can always get in touch with a human at support@github.com. For the more technical minded folks who want to skip the help docs: your site's DNS records are pointed to a deprecated IP address.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions please contact us at https://github.com/contact.
```

@asmeurer is it possible to make these changes in DNS server? It says that it'll speed up the website.

**Comment by debugger22** [comment]
Here's a blog post for the same: https://github.com/blog/1917-github-pages-legacy-ip-deprecation

**Comment by certik** [comment]
I looked into it about a year ago. If you tell me exactly what to set, I'll be happy to do it.

**Comment by certik** [comment]
Here is info about it:

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

So one needs to carefully study those and then see what exact change to make. Our dns provider is linode.com.

**Comment by asmeurer** [comment]
I was going to bug you about this at the summit but I forgot.

**Comment by asmeurer** [comment]
Is it possible for you to give me admin access on Linode?

**Comment by roryokane** [comment]
This is more urgent now that the [week-long brownout](https://github.com/blog/1925-github-pages-legacy-ip-brownout) has started for misconfigured sites. [docs.sympy.org](http://docs.sympy.org/) currently serves a “Site temporarily disabled” page because of this.

[On December 1st](https://github.com/blog/1917-github-pages-legacy-ip-deprecation), sites with the old configuration will be permanently disabled.

**Comment by certik** [comment]
Thanks. We actually already fixed it, see our mailinglist for updates. docs.sympy.org works for me now. Wait a few hours for your local dns server to update and it will work for you as well.
