### ISSUE TITLE
Error in SymPy tutorial - Gotchas

### ISSUE THREAD

**Issue by laxmena** [sympy/sympy_doc#21]
link: http://docs.sympy.org/latest/tutorial/gotchas.html

> > > > Eq(x + 1, 4)
> > > > x + 1 == 4

Actually the SymPy Live yields different value for the above part,
SymPy Live gives result to **Eq(x + 1,4)** as **x+1=4** and not _x + 1 == 4_

**Comment by sidhantnagpal** [comment]
`x + 1 = 4` is the correct representation of the object `Eq(x + 1, 4)`. (`Eq` is used to create symbolic equalities)
`==` is a comparison operator.
