### ISSUE TITLE
Redirection loop in docs.sympy.org/latest

### ISSUE THREAD

**Issue by yyogo** [sympy/sympy_doc#34]
It looks like [docs.sympy.org](https://docs.sympy.org) redirects to [/latest](https://docs.sympy.org/latest/index.html), which redirects to [/1.5.1](https://docs.sympy.org/latest/index.html), which redirects to latest again...

Tested on multiple browsers & devices

**Comment by ShubhamKJha** [comment]
As of now, it works perfectly.

**Comment by oscarbenjamin** [comment]
I'm still seeing the redirect loop. I pushed what I thought was a fix...

**Comment by oscarbenjamin** [comment]
Ah, okay. Looks like it's working now. Can you confirm @rumbah?
